Update backend.yml

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -21,7 +21,10 @@ jobs:
      
      - name: Build with Maven (skip tests optional)
        run: mvn -B -DskipTests=true clean package
-       # If you want to skip tests in CI change -DskipTests=true
+     - name: Check secrets present
+       run: |
+         if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "DOCKERHUB_USERNAME missing" && exit 1; fi
+         if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "DOCKERHUB_TOKEN missing" && exit 1; fi
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
